### PR TITLE
OCPBUGS-37455:  Revert "STOR-1593: Rebase to upstream v5.0.1 for 4.17"

### PR DESCRIPTION
**Pull request by bertinatto**
Reverts openshift/csi-external-provisioner#98

### CODE REVIEW

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-csi

**Comment by gnufied** [comment]
So, this PR isn't mergeable because of subtree check that is failing. I opened another one - https://github.com/openshift/csi-external-provisioner/pull/102 which fixes this. 

/close

**Pull request closed without merging**
