### PR TITLE
STOR-1593: Rebase to upstream v5.0.1 for 4.17

### PR DESCRIPTION
**Pull request by rhrmo**
Do not merge this PR before https://github.com/openshift/cluster-storage-operator/pull/482 is merged. We need provisioner to have updated permission (added "patch" permission), otherwise the CI will not run correctly.

Diff to upstream v5.0.1:
https://github.com/kubernetes-csi/external-provisioner/compare/v5.0.1...rhrmo:rebase-v5.0.1

Changes between 4.0.1 (OCP 4.16) and 5.0.1:

* Feature gate Topology is enabled by default. This feature gate is already GA and will be removed in a future release. CSI drivers are required to report capability VOLUME_ACCESSIBILITY_CONSTRAINTS correctly: when a CSI drivers reports the capability, topology is enabled in the external-provisioner. When the driver does not report it, external-provisioner disables topology support. (https://github.com/kubernetes-csi/external-provisioner/pull/1167, [@huww98](https://github.com/huww98))
* The external-provisioner now needs permissions to patch persistentvolumes. Please update your RBACs appropriately. See the linked pull request for an example. (https://github.com/kubernetes-csi/external-provisioner/pull/1155, [@carlory](https://github.com/carlory))
* Added support for PVC annotations in csi.storage.k8s.io/provisioner-secret-name StorageClass parameters. For example: csi.storage.k8s.io/provisioner-secret-name: ${pvc.annotations['xyz']}. (https://github.com/kubernetes-csi/external-provisioner/pull/1196, [@hoyho](https://github.com/hoyho))
* Promote HonorPVReclaimPolicy to beta. (https://github.com/kubernetes-csi/external-provisioner/pull/1209, [@carlory](https://github.com/carlory))

Full upstream changelogs: 
https://github.com/kubernetes-csi/external-provisioner/blob/v5.0.1/CHANGELOG/CHANGELOG-5.0.md

@openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
@rhrmo CI will keep failing until we have go 1.22.3 in CI: https://issues.redhat.com/browse/ART-9927 -> otherwise looks good.

**Comment by duanwei33** [comment]
CI looks good.
/label qe-approved

**Pull request merged**
