### PR TITLE
STOR-1020: Rebase `external-provisioner` to v3.4.0 for OCP 4.13

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v3.4.0:
https://github.com/kubernetes-csi/external-provisioner/compare/v3.4.0...mpatlasov:rebase-3.4.0

Major changes between 3.3.0 (OCP 4.12) and 3.4.0:

Add support for cross-namespace data sources alpha feature (https://github.com/kubernetes-csi/external-provisioner/pull/805, [@ttakahashi21]
Register metrics exposed by sig-storage-lib (https://github.com/kubernetes-csi/external-provisioner/pull/792, [@RaunakShah](https://github.com/RaunakShah))
Update the annotation that needs to be applies to VolumeSnapshotContents from snapshot.storage.kubernetes.io/allowVolumeModeChange to snapshot.storage.kubernetes.io/allow-volume-mode-change (https://github.com/kubernetes-csi/external-provisioner/pull/791, [@RaunakShah](https://github.com/RaunakShah))
Update go to 1.19 and dependencies for k8s v1.26.0 (https://github.com/kubernetes-csi/external-provisioner/pull/834, [@sunnylovestiramisu](https://github.com/sunnylovestiramisu))

Full changelogs:

https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.4.0

@openshift/storage

### CODE REVIEW

**Comment by mpatlasov** [comment]
/retitle STOR-1020: Rebase `external-provisioner` to v3.4.0 for OCP 4.13

**Comment by duanwei33** [comment]
Checked the CI results look good for sidecar rebase.

**Pull request merged**
