### PR TITLE
Bug 1876791: Rebase to v2.0.0

### PR DESCRIPTION
**Pull request by jsafrane**
Rebase to v2.0.0 for OCP 4.6.

Diff to upstream v2.0.0:
https://github.com/kubernetes-csi/external-provisioner/compare/v2.0.0...jsafrane:rebase-v2.0.0

@openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by jsafrane** [comment]
/hold
for https://github.com/openshift/aws-ebs-csi-driver-operator/pull/87

**Comment by jsafrane** [comment]
The last failure was caused by old aws-ebs image used in tests (still uses `--provisioner` argument)

**Comment by jsafrane** [comment]
Flake: https://bugzilla.redhat.com/show_bug.cgi?id=1877338

**Pull request merged**
