### PR TITLE
Rebase to v1.1.1

### PR DESCRIPTION
**Pull request by jsafrane**
* Merged v1.1.1 into openshift/master.
* Manually pruned content of vendor/github.com/kubernetes-csi/csi-lib-utils/ to contain only the files that v1.1.1 tag contains. From some reason git merge added some files there (wrong deletion detection?)
* Checked that diff to upstream v1.1.1 contains only Dockerfiles and OWNERS, i.e. the only files we changed in OpenShift repo.

### CODE REVIEW

**Comment by jsafrane** [comment]
cc @openshift/storage

**Comment by gnufied** [comment]
@jsafrane are the unit tests failure real?

**Comment by jsafrane** [comment]
gofmt failed, it looks like upstream and OpenShift uses different go versions. I'll investigate.

**Comment by jsafrane** [comment]
Diff between upstream v1.1.0 tag and this PR: https://github.com/kubernetes-csi/livenessprobe/compare/v1.1.0...jsafrane:rebase-v1.1.0

**Comment by jsafrane** [comment]
Updated to go 1.11.

I plan to update all the other CSI repos to 1.11, but outside of rebase PR, it's quite messy already.

**Comment by jsafrane** [comment]
> Updated to go 1.11.

That did not work out, I need to update the prow job itself. Restored 1.10 to have as little changes in this PR as possible.

**Comment by jsafrane** [comment]
/retest
with new golang in prow job

**Pull request merged**
